const $ = (s, root=document) => root.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = value => Number(value || 0).toLocaleString('en-US', {maximumFractionDigits:0});
const usd = value => '$' + Number(value || 0).toLocaleString('en-US', {minimumFractionDigits:2,maximumFractionDigits:2});
const paths = {
  grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',
  box:'m3 7 9-4 9 4v10l-9 4-9-4Z m0 0 9 4 9-4 M12 11v10 M7 5l10 4',
  users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M17 4a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-3.9',
  order:'M7 3h10l3 3v15H4V3h3 M8 9h8 M8 13h8 M8 17h5',
  quote:'M9 3H5v18h14V3h-4 M9 3v4h6V3 M8 12h8 M8 16h5',
  spark:'m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3Z M20 2v4 M18 4h4',
  book:'M12 5C9 3 5 3 2 4v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1v15',
  settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1Z',
  arrow:'M4 12h16 m-6-6 6 6-6 6',
  chevron:'m9 5 7 7-7 7',
  search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',
  bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9 M10 21h4',
  plus:'M12 5v14 M5 12h14',
  trend:'m3 17 6-6 4 4 8-10 M15 5h6v6',
  dollar:'M12 2v20 M17 6H9a4 4 0 0 0 0 8h6a4 4 0 0 1 0 8H6',
  clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l4 2',
  shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z m-4 9 3 3 5-6',
  globe:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M3 12h18 M12 3c-5 5-5 13 0 18 5-5 5-13 0-18',
  logout:'M9 4H4v16h5 M10 12h11 m-4-4 4 4-4 4',
  close:'m6 6 12 12 M18 6 6 18',
  check:'m5 12 4 4L19 6',
  menu:'M4 6h16 M4 12h16 M4 18h16',
  refresh:'M20 7v5h-5 M4 17v-5h5 M5 7a8 8 0 0 1 14-1l1 6 M4 12l1 6a8 8 0 0 0 14-1',
  chart:'M4 3v18h17 M8 16v-5 M13 16V7 M18 16v-9',
};
const icon = (name, cls='') => `<svg class="icon ${cls}" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[name]||paths.spark}"/></svg>`;
const navs = [['overview','grid','工作台概览'],['products','box','选品与商品'],['quotes','quote','智能报价'],['orders','order','订单与履约'],['customers','users','客户管理'],['agents','spark','AI 助手中心'],['knowledge','book','企业知识库'],['system','settings','集成与审计']];
const names = {admin:'管理员',sales:'业务员',operations:'跟单员',viewer:'只读访客'};
const stageNames = {sampling:'打样确认',production:'大货生产',inspection:'质量检验',shipping:'物流出运',delivered:'已交付',closed:'已结清'};
const state = {user:null, config:{}, page:'overview', selectedAgent:'merchandiser', query:'', orderFilter:'all', products:[], customers:[], orders:[], quotes:[], agents:[], generation:0};
let toastTimer;
function toast(message, error=false) { const el=$('#toast'); el.textContent=message;el.className='show'+(error?' error':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className='',4500); }
async function api(path, options={}) {
  const response=await fetch('/api'+path,{credentials:'same-origin',...options,headers:{'Content-Type':'application/json',...options.headers}});
  let data;try{data=await response.json();}catch{throw new Error('服务返回异常，请稍后重试');}
  if(!response.ok){if(response.status===401 && state.user){state.user=null;renderLogin();}throw new Error(Array.isArray(data.detail)?data.detail.map(x=>x.msg).join('；'):data.detail||'请求失败');}
  return data;
}
const post = (path, body={}) => api(path,{method:'POST',body:JSON.stringify(body)});
const badge = (text, kind='') => `<span class="badge ${esc(kind)}">${esc(text)}</span>`;
const can = (...roles) => roles.includes(state.user.role);
function empty(message='暂无记录') {return `<div class="empty">${esc(message)}</div>`;}
function shirt(color, type='') {
  const palette={sage:['#ebeee4','#a5b5a0'],sand:['#efebe2','#c2b297'],rose:['#f1e7e2','#c9a799'],blue:['#e6eaeb','#879caa'],lavender:['#eceaf0','#bbb4c9'],slate:['#e9eae5','#979e8c']};
  const [bg,cloth]=palette[color]||palette.sage;
  let shape=type==='裤装'?`<path d="M70 34h60l-4 100h-23l-4-64-4 64H72Z" fill="${cloth}"/><path d="M71 43h58 M98 35v34" stroke="#fff" opacity=".4" fill="none"/>`:
    `<path d="m77 36-25 12-18 30 23 12 12-17 ${type==='连衣裙'?' -8 63h78l-8-63':'0 58h62V73'} 12 17 23-12-18-30-25-12q-23 16-46 0Z" fill="${cloth}"/><path d="m77 36 12 15 11-9 11 9 12-15 M100 44v83 M73 70v55 M127 70v55" stroke="#fff" stroke-width="1.1" opacity=".45" fill="none"/><path d="M79 66h13v13H79" fill="none" stroke="#fff" opacity=".35"/><circle cx="104" cy="66" r="1.2" fill="#fff" opacity=".7"/><circle cx="104" cy="81" r="1.2" fill="#fff" opacity=".7"/><circle cx="104" cy="96" r="1.2" fill="#fff" opacity=".7"/>`;
  return `<svg viewBox="0 0 200 160" aria-hidden="true"><rect width="200" height="160" fill="${bg}"/><ellipse cx="100" cy="142" rx="42" ry="4" fill="#4c5942" opacity=".06"/><path d="M97 24q0-8 6-5t-3 11l-26 9h52l-26-9" stroke="#acaa97" stroke-width="1.5" fill="none"/>${shape}</svg>`;
}
function renderLogin() {
  $('#app').innerHTML=`<div class="login-page"><section class="login-story"><div class="brand"><span class="brand-mark">H</span>Harbor OS</div><div><div class="eyebrow">YOUR BUSINESS, CONNECTED.</div><h1>让跨境生意，<br>更从容一点。</h1><p>从第一份询盘，到每一次安心交付。<br>连接业务、知识与 AI 的企业工作台。</p></div><p>HARBOR OS / 跨境电商 AI 工作台</p><div class="login-art"></div></section><section class="login-box"><form id="login-form" class="login-form"><div class="eyebrow">WELCOME ABOARD</div><h2>欢迎回到 Harbor</h2><p>登录你的企业空间，开始今天的工作。</p><label class="field">工作邮箱<input class="input" name="email" type="email" autocomplete="username" required value="${state.config.demo?'admin@harbor.local':''}" placeholder="name@company.com"></label><label class="field">密码<input class="input" name="password" type="password" autocomplete="current-password" required value="${state.config.demo?'HarborDemo2026!':''}" placeholder="输入登录密码"></label><div class="login-error" role="alert"></div><button class="btn primary" type="submit">登录工作台 ${icon('arrow')}</button>${state.config.demo?'<div class="login-demo">当前为本地演示环境，已填入演示管理员账号。<br>业务员 / 跟单员：sales / ops @harbor.local<br>统一演示密码：HarborDemo2026!</div>':''}</form></section></div>`;
}
function shell() {
  $('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#overview"><span class="brand-mark">H</span><span>Harbor OS<small>CROSS-BORDER WORKSPACE</small></span></a><div class="workspace"><div class="workspace-icon">${icon('globe')}</div><div><strong>远舟 · 跨境事业部</strong><small>Harbor Commerce Workspace</small></div></div><div class="nav-caption">WORKSPACE / 业务空间</div><nav>${navs.slice(0,5).map(navButton).join('')}<div class="nav-caption" style="margin-top:26px">INTELLIGENCE / 智能协作</div>${navs.slice(5).filter(n=>n[0]!=='system'||can('admin')).map(navButton).join('')}</nav><div class="sidebar-bottom"><div class="sidebar-tip"><strong>✧ 业务经验，成为团队能力</strong><p>让每次判断有据可循，<br>让每次协作都有迹可查。</p></div><div class="profile"><div class="avatar">${esc(state.user.name[0])}</div><div>${esc(state.user.name)}<small>${esc(names[state.user.role])} · 远舟跨境</small></div><button class="icon-btn" data-action="logout" aria-label="退出登录">${icon('logout')}</button></div></div></aside><main class="main"><header class="topbar"><div class="breadcrumb"><button class="icon-btn mobile-menu" data-action="menu" aria-label="切换导航">${icon('menu')}</button>工作空间 ${icon('chevron')} <strong id="crumb">工作台概览</strong></div><div class="top-actions"><button class="search-shortcut" data-nav="knowledge">${icon('search')} 搜索企业知识 <kbd>⌘ K</kbd></button><span class="status-dot">${state.config.demo?'演示环境':'企业空间'}</span><button class="icon-btn" data-nav="orders" data-risk="true" aria-label="查看订单预警">${icon('bell')}</button><div class="avatar">${esc(state.user.name[0])}</div></div></header><div class="content" id="content"></div></main>`;
}
function navButton([id,ico,label]) {return `<button class="nav-item${state.page===id?' active':''}" data-nav="${id}">${icon(ico)}${label}${id==='agents'?'<span class="nav-dot"></span>':''}</button>`;}
function heading(title,subtitle,actions='',eyebrow='YOUR CROSS-BORDER WORKSPACE') {
  return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-actions">${actions}</div></div>`;
}
const footer=()=>`<footer class="footer"><span>Harbor OS · 连接每一步跨境生意</span><span>${state.config.demo?'演示业务数据 · ':''}金额 USD / 时间按当前浏览器显示</span></footer>`;
async function navigate(page, updateHash=true) {
  if(!state.user)return;
  if(!navs.some(n=>n[0]===page))page='overview';
  if(page==='system'&&!can('admin'))page='overview';
  state.page=page;state.query='';const generation=++state.generation;
  if(updateHash)history.replaceState(null,'','#'+page);
  $$('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.nav===page));
  $('.sidebar')?.classList.remove('open');$('#crumb').textContent=navs.find(n=>n[0]===page)[2];$('#content').innerHTML='<div class="loading">正在加载业务数据…</div>';
  try {
    const html=await ({overview:renderOverview,products:renderProducts,quotes:renderQuotes,orders:renderOrders,customers:renderCustomers,agents:renderAgents,knowledge:renderKnowledge,system:renderSystem}[page])();
    if(generation===state.generation){$('#content').innerHTML=html+footer();window.scrollTo(0,0);}
  } catch(err) {if(generation===state.generation&&$('#content'))$('#content').innerHTML=empty(err.message)+`<button class="btn" data-action="reload">重新加载</button>`;}
}
const $$ = (s,root=document)=>[...root.querySelectorAll(s)];
async function renderOverview() {
  const d=await api('/dashboard');state.orders=d.orders;
  const high=d.orders.filter(o=>o.risk.level==='high');
  const today=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
  return heading(`${esc(state.user.name)}，今天也稳步向前。`,'业务全貌，一目了然。让每一个决策，都有更好的依据。',`<button class="btn">${icon('clock')}${esc(today)}</button><button class="btn primary" data-nav="agents">${icon('spark')}启动 AI 助手</button>`,'OVERVIEW / 工作台概览')+
    `<section class="hero"><div class="hero-copy"><span class="pill">${icon('spark')} HARBOR INTELLIGENCE</span><h2>从发现机会，到交付价值。</h2><p>你的跨境业务，正在有序运转。<br>今天有 ${d.active_orders} 笔订单正在履约，${high.length} 笔交期风险值得优先关注。</p><button class="btn primary" data-agent="merchandiser">查看 AI 跟单建议 ${icon('arrow')}</button></div><svg class="hero-art" viewBox="0 0 440 240" aria-hidden="true"><defs><pattern id="dots" width="16" height="16" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#aec1a2" opacity=".45"/></pattern></defs><rect width="440" height="240" fill="url(#dots)"/><g transform="translate(210 135)" fill="none" stroke="#b7caaa" stroke-width=".8"><circle r="112"/><ellipse rx="60" ry="112"/><ellipse rx="100" ry="112"/><ellipse rx="112" ry="40"/><ellipse rx="112" ry="80"/><path d="M-112 0h224M0-112v224"/></g><path d="M92 163Q227-15 362 85" fill="none" stroke="#7b9b68" stroke-dasharray="4 4"/><circle cx="92" cy="163" r="5" fill="#72975d"/><circle cx="362" cy="85" r="5" fill="#72975d"/></svg><div class="hero-tag">让协作跨越时区<strong>GLOBAL, CONNECTED.</strong></div><div class="hero-tag second">✦ 每一步，都有据可循</div></section>`+
    `<section class="metrics">${metric('订单合同金额',usd(d.order_value),'dollar','已录入订单','全部订单累计')}${metric('履约中的订单',d.active_orders+'<span class="unit">笔</span>','order',d.order_count+' 笔总订单','打样 → 出运')}${metric('待处理交期风险',d.at_risk+'<span class="unit">笔</span>','clock','优先关注','根据生产进度与交期',true)}${metric(can('admin')?'估算订单毛利率':'已完成交付',can('admin')?(d.margin*100).toFixed(1)+'<span class="unit">%</span>':d.orders.filter(o=>['delivered','closed'].includes(o.stage)).length+'<span class="unit">笔</span>','chart',can('admin')?'按成本快照计算':'已交付 / 已结清',can('admin')?'非财务净利润':'订单状态实时统计')}</section>`+
    `<div class="grid-main"><section class="panel"><div class="panel-head"><div><h2>业务渠道概览</h2><p>不同渠道的订单合同金额分布</p></div><div class="panel-tabs"><span class="selected">累计金额</span><span>USD</span></div></div><div class="panel-body">${channelChart(d.channels)}<div class="legend"><span>已录入订单合同金额</span></div></div></section><section class="panel"><div class="panel-head"><h2>你的 AI 业务伙伴</h2><button class="btn text" data-nav="agents">全部助手 ${icon('arrow')}</button></div><div class="assistant-feature"><div class="assistant-feature-head"><span class="ai-symbol">${icon('spark')}</span>AI 跟单员已就绪</div><p>连接订单与企业 SOP，识别潜在交期风险。<br>从业务数据出发，生成可执行的跟进建议。</p><button class="btn" data-agent="merchandiser">运行交期检查 ${icon('arrow')}</button></div><div class="agent-shortcuts"><button class="agent-shortcut" data-agent="buyer">${icon('trend')}AI 选品买手</button><button class="agent-shortcut" data-agent="quote">${icon('quote')}AI 报价助手</button><button class="agent-shortcut" data-agent="support">${icon('users')}AI 客服助手</button></div></section></div>`+
    `<div class="grid-main"><section class="panel"><div class="panel-head"><div><h2>订单履约动态</h2><p>关注关键节点，让交付更可控</p></div><button class="btn text" data-nav="orders">查看全部 ${icon('arrow')}</button></div>${orderTable(d.orders.slice(0,4),true)}<div class="panel-footer"><span>共 ${d.order_count} 笔订单 · 数据来自当前企业</span><span>持续跟进 · 安心交付</span></div></section><section class="panel"><div class="panel-head"><div><h2>值得关注的商品</h2><p>按内部近 30 天销售增长排序</p></div><button class="btn text" data-nav="products">${icon('arrow')}</button></div><div class="opportunities">${d.products.map(p=>`<div class="product-row"><div class="product-thumb">${shirt(p.color)}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.sku)} · ${number(p.sales_30d)} 件 / 30 天</p></div><span class="growth">+${p.growth}%</span></div>`).join('')}</div><div class="panel-footer"><span>内部销售样本，不代表全市场趋势</span></div></section></div>`;
}
function metric(label,value,ico,accent,note,warn=false){return `<div class="metric"><div class="metric-top">${label}${icon(ico)}</div><div class="metric-value">${value}</div><div class="metric-foot"><b class="${warn?'warn':''}">${accent}</b>${note}</div></div>`;}
function channelChart(channels){
  const max=Math.max(...channels.map(c=>c.value),1);const width=600;const gap=width/Math.max(channels.length,1);
  return `<svg class="chart" viewBox="0 0 640 200" role="img" aria-label="各渠道累计订单金额柱状图">${[0,1,2,3].map(i=>`<line x1="43" x2="630" y1="${20+i*47}" y2="${20+i*47}" stroke="#eef1ea" stroke-dasharray="4 5"/><text x="0" y="${23+i*47}" class="chart-label">${number(max*(3-i)/3/1000)}k</text>`).join('')}${channels.map((c,i)=>{const h=c.value/max*139;return `<rect x="${60+i*gap}" y="${160-h}" width="${Math.min(gap-42,72)}" height="${h}" fill="${i%2?'#bacdb0':'#769c7c'}" rx="5"/><text x="${60+i*gap+Math.min(gap-42,72)/2}" y="${151-h}" class="chart-label" text-anchor="middle">$${number(c.value)}</text><text x="${60+i*gap+Math.min(gap-42,72)/2}" y="185" class="chart-label" text-anchor="middle">${esc(c.name)}</text>`;}).join('')}</svg>`;
}
function orderTable(orders,compact=false){
  if(!orders.length)return empty('暂无符合条件的订单');
  return `<div class="table-wrap"><table><thead><tr><th>订单 / 客户</th>${compact?'':'<th>商品 / 数量</th><th>金额 / 已收</th>'}<th>当前节点</th><th>出运日期</th><th>风险状态</th>${compact?'':'<th>操作</th>'}</tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${esc(o.number)}</strong><small>${esc(o.customer_name)}</small></td>${compact?'':`<td>${esc(o.product_name)}<small>${number(o.quantity)} 件</small></td><td>${usd(o.total)}<small>已收 ${usd(o.paid)}</small></td>`}<td>${badge(o.stage_name,['shipping','delivered','closed'].includes(o.stage)?'':'blue')}<div class="progress-row" style="margin-top:9px"><div class="progress"><i style="width:${o.progress}%"></i></div>${o.progress}%</div></td><td>${esc(o.due_date)}${compact?'':`<small>${esc(o.channel)}</small>`}</td><td title="${esc(o.risk.reason)}">${badge(o.risk.label,o.risk.level)}</td>${compact?'':`<td><button class="btn text" data-order="${esc(o.id)}">查看 / 跟进 ${icon('chevron')}</button></td>`}</tr>`).join('')}</tbody></table></div>`;
}
async function renderProducts(){state.products=await api('/products');return heading('每一款，都有生意的可能。','连接商品、销售表现与库存，辅助下一次选品决策。',`<button class="btn primary" data-agent="buyer">${icon('spark')}AI 选品建议</button>`,'PRODUCTS / 选品与商品')+`<div class="filterbar"><input class="input" data-search="products" placeholder="搜索商品名称或 SKU" aria-label="搜索商品"><span class="muted" style="font-size:11px">${state.products.length} 款商品 · 参考售价 USD</span></div><div class="product-grid" id="product-list">${productCards(state.products)}</div>`;}
function productCards(products){return products.map(p=>`<article class="product-card"><div class="product-visual">${shirt(p.color,p.category)}${badge(p.category)}</div><div class="product-card-body"><small>${esc(p.sku)}</small><h3>${esc(p.name)}</h3><small>${esc(p.material)}</small><div class="product-detail"><span>库存 ${number(p.stock)} 件</span><span>近 30 天 ${number(p.sales_30d)} 件</span></div><div class="product-detail"><span>起订 ${p.moq} 件 · 交期 ${p.lead_days} 天</span><span style="color:${p.growth>=0?'#769d6a':'#b58562'}">${p.growth>=0?'+':''}${p.growth}%</span></div><div class="product-price"><strong>${usd(p.price_usd)}<small>/ 件</small></strong>${can('admin','sales')?`<button class="btn small" data-quote-product="${esc(p.id)}">创建报价 ${icon('arrow')}</button>`:''}</div></div></article>`).join('')||empty('未找到匹配商品');}
async function renderOrders(){state.orders=await api('/orders');return heading('每一单，都稳稳向前。','跟踪打样、生产、验货与出运，提前看见交付风险。',`<button class="btn primary" data-agent="merchandiser">${icon('spark')}检查交期风险</button>`,'ORDERS / 订单与履约')+`<div class="filterbar"><input class="input" data-search="orders" placeholder="搜索订单号、客户或商品" aria-label="搜索订单">${[['all','全部订单'],['risk','风险订单'],['production','生产中'],['shipping','已出运']].map(([key,label])=>`<button class="filter-pill ${state.orderFilter===key?'active':''}" data-order-filter="${key}">${label}</button>`).join('')}</div><section class="panel" id="order-list">${filteredOrders()}</section>`;}
function filteredOrders(){return orderTable(state.orders.filter(o=>JSON.stringify([o.number,o.customer_name,o.product_name]).toLowerCase().includes(state.query.toLowerCase())).filter(o=>state.orderFilter==='all'||(state.orderFilter==='risk'?o.risk.level!=='normal':o.stage===state.orderFilter)));}
async function renderQuotes(){if(!can('admin','sales'))return empty('当前角色无报价权限，请使用业务员或管理员账号。');[state.products,state.customers,state.quotes]=await Promise.all([api('/products'),api('/customers'),api('/quotes')]);return heading('好报价，始于清晰的成本。','让汇率、运费与利润目标都有据可算，审批后再转为订单。','', 'QUOTATIONS / 智能报价')+`<div class="quote-layout"><section class="panel"><div class="panel-head"><h2>创建报价方案</h2>${badge('USD / 美元')}</div><form id="quote-form" class="panel-body"><div class="form-grid"><label class="field full">商品<select name="product_id">${state.products.map(p=>`<option value="${esc(p.id)}" ${state.quoteProduct===p.id?'selected':''}>${esc(p.name)} · MOQ ${p.moq}</option>`).join('')}</select></label><label class="field full">客户<select name="customer_id">${state.customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} / ${esc(c.country)}</option>`).join('')}</select></label><label class="field">采购数量<input class="input" name="quantity" type="number" min="1" max="1000000" value="500" required></label><label class="field">贸易术语<select name="incoterm"><option value="FOB">FOB · 离岸价</option><option value="DDP">DDP · 完税交货估算</option></select></label>${numericField('人民币 / 美元汇率','fx_rate','7.20','.0001','.01','1000')}${numericField('目标毛利率 %','margin','30','.1','5','80')}${numericField('单件包装成本 CNY','packaging_cny','3','.01','0','10000')}${numericField('单件国内物流 CNY','domestic_cny','2','.01','0','10000')}${numericField('单件国际运费 USD（DDP）','freight_usd','1.5','.01','0','10000')}${numericField('估算关税 %（DDP）','duty_rate','12','.1','0','100')}<p class="form-note field full">工厂成本包含面辅料及加工；FOB 自动排除国际运费及关税。低于 25% 毛利需管理员审批。汇率与税率均为人工输入。</p></div><div class="form-actions"><button class="btn" type="submit" name="action" value="preview">计算预览</button><button class="btn primary" type="submit" name="action" value="save">保存并提交审批 ${icon('arrow')}</button></div></form></section><section class="panel"><div class="panel-head"><h2>成本与利润拆解</h2>${icon('chart')}</div><div class="panel-body" id="quote-result">${empty('填写左侧报价信息，点击「计算预览」\n查看单件成本、建议售价与订单总额。')}</div></section></div><section class="panel mt"><div class="panel-head"><h2>报价记录与审批</h2><span class="muted" style="font-size:11px">确认后可转订单 · 不自动对外发送</span></div><div id="quotes-list">${quoteTable()}</div></section>`;}
function numericField(label,name,value,step,min,max){return `<label class="field">${label}<input class="input" name="${name}" type="number" step="${step}" min="${min}" max="${max}" value="${value}" required></label>`;}
function quoteTable(){return state.quotes.length?`<div class="table-wrap"><table><thead><tr><th>商品 / 客户</th><th>数量</th><th>单价 / 总额</th><th>目标毛利</th><th>状态</th><th>操作</th></tr></thead><tbody>${state.quotes.map(q=>`<tr><td><strong>${esc(q.product_name)}</strong><small>${esc(q.customer_name)}</small></td><td>${number(q.quantity)} 件</td><td>${usd(q.unit_price)}<small>合计 ${usd(q.total)}</small></td><td>${(Number(q.margin)*100).toFixed(1)}%</td><td>${badge({pending:'待审批',approved:'已审批',converted:'已转单'}[q.status],q.status==='pending'?'medium':'')}</td><td>${q.status==='pending'?`<button class="btn small" data-approve="${esc(q.id)}">人工审批</button>`:q.status==='approved'?`<button class="btn small primary" data-convert="${esc(q.id)}">确认转订单</button>`:'已完成'}</td></tr>`).join('')}</tbody></table></div>`:empty('暂无报价。从上方创建第一份报价开始。');}
function quoteResult(r){return r.components.map(c=>`<div class="cost-line"><span>${esc(c.name)}</span><strong>${usd(c.value)}</strong></div>`).join('')+`<div class="cost-line"><span>单件总成本</span><strong>${usd(r.unit_cost_usd)}</strong></div><div class="quote-total"><span>建议单价 · ${esc(r.incoterm)}</span><strong>${usd(r.unit_price)} <span>/ 件</span></strong><small>订单总额 ${usd(r.total)} · 实际毛利 ${(Number(r.actual_margin)*100).toFixed(2)}%</small></div>${r.warnings.map(w=>`<p class="form-note">${esc(w)}</p>`).join('')}${r.requires_admin?'<div class="notice mt">目标毛利低于 25%，需要管理员审批。</div>':''}`;}
async function renderCustomers(){if(!can('admin','sales','operations'))return empty('当前角色无权访问客户资料。');state.customers=await api('/customers');return heading('好的关系，成就长久的生意。','沉淀客户信息，把每一次跟进变成下一次合作的起点。',can('admin','sales')?`<button class="btn" data-agent="sales">${icon('spark')}AI 跟进建议</button><button class="btn primary" data-action="new-customer">${icon('plus')}新增客户</button>`:'','CUSTOMERS / 客户管理')+`<div class="filterbar"><input class="input" data-search="customers" placeholder="搜索客户、国家或渠道" aria-label="搜索客户"><span class="muted" style="font-size:11px">${state.customers.length} 位客户</span></div><section class="panel" id="customer-list">${customerTable(state.customers)}</section>`;}
function customerTable(customers){return customers.length?`<div class="table-wrap"><table><thead><tr><th>客户名称</th><th>市场 / 渠道</th><th>合作阶段</th><th>历史合作金额</th><th>最近联系</th><th>负责人</th><th>操作</th></tr></thead><tbody>${customers.map(c=>`<tr><td><div class="customer-name"><div class="avatar">${esc(c.name.slice(0,1))}</div><div><strong>${esc(c.name)}</strong><small>${esc(c.email)}</small></div></div></td><td>${esc(c.country)}<small>${esc(c.channel)}</small></td><td>${badge(c.stage,c.stage==='待唤醒'?'medium':'')}</td><td>${usd(c.total_usd)}</td><td>${esc(c.last_contact)}</td><td>${esc(c.owner)}</td><td>${can('admin','sales')?`<button class="btn text" data-contact="${esc(c.id)}">记录已联系</button>`:'只读'}</td></tr>`).join('')}</tbody></table></div>`:empty('未找到客户');}
const agentQuestions={buyer:'结合销量、增长率和库存，为我推荐值得关注的商品。',sales:'哪些客户值得优先跟进？请给出客户唤醒建议。',merchandiser:'检查当前订单的交期风险，并给出跟进建议。',quote:'检查待审批报价，并说明低毛利报价审批要求。',support:'客户询问验货标准，请查找 AQL 和样品要求。',analyst:'分析订单金额、待收款和估算毛利情况。',retro:'复盘当前履约异常，列出需要核实的原因和改进方向。'};
async function renderAgents(){const [agents,runs]=await Promise.all([api('/agents'),api('/agents/runs')]);state.agents=agents;if(!agents.find(a=>a.id===state.selectedAgent)?.available)state.selectedAgent=agents.find(a=>a.available)?.id;return heading('把经验，变成可以执行的能力。','7 类业务助手，共享企业知识与受控工具；每次执行都有证据和记录。',badge(state.config.llm==='rules'?'规则与检索模式':'Ollama 已配置'),'INTELLIGENCE / AI 助手中心')+`<div class="agent-grid">${agents.map((a,i)=>`<button class="agent-card ${a.id===state.selectedAgent?'selected':''}" data-select-agent="${a.id}" ${a.available?'':'disabled'}><div class="agent-card-top"><span class="ai-symbol">${icon(['trend','users','order','quote','book','chart','refresh'][i])}</span>${badge(a.available?'可运行':'无权限',a.available?'':'gray')}</div><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p></button>`).join('')}</div><section class="panel"><div class="panel-head"><h2 id="selected-agent-name">${esc(agents.find(a=>a.id===state.selectedAgent)?.name||'业务助手')}</h2><span class="muted" style="font-size:10px">受控流程 · 不自动对外发送或修改业务</span></div><div class="panel-body"><form id="agent-form" class="agent-input-row"><textarea class="input" name="question" maxlength="2000" required aria-label="助手任务">${agentQuestions[state.selectedAgent]}</textarea><button class="btn primary" type="submit">${icon('spark')}运行助手</button></form><div id="agent-output" class="agent-output"></div></div></section><section class="panel mt"><div class="panel-head"><h2>最近执行</h2><span class="muted" style="font-size:10px">仅展示当前用户的执行记录</span></div><div id="run-history">${runHistory(runs)}</div></section>`;}
function runHistory(runs){state.runs=runs;return runs.length?`<div class="table-wrap"><table><thead><tr><th>助手</th><th>任务</th><th>执行方式</th><th>耗时</th><th>结果</th></tr></thead><tbody>${runs.slice(0,8).map(r=>`<tr><td>${esc(state.agents.find(a=>a.id===r.agent)?.name||r.agent)}</td><td title="${esc(r.question)}">${esc(r.question.slice(0,36))}${r.question.length>36?'…':''}</td><td>${esc(r.model_mode)}</td><td>${number(r.duration_ms)} ms</td><td><button class="btn text" data-run="${esc(r.id)}">查看记录</button></td></tr>`).join('')}</tbody></table></div>`:empty('暂无执行记录。运行一次助手，即可查看工具调用与证据。');}
function agentResult(run){const r=run.result;return `<div class="result-summary">${esc(r.summary)}</div>${r.model_error?`<div class="notice">${esc(r.model_error)}</div>`:''}${r.items.map(item=>`<div class="result-item"><strong>${esc(item.label)}</strong><p>${esc(item.detail)}</p></div>`).join('')}${r.actions.length?`<div class="result-item"><strong>建议下一步</strong>${r.actions.map(a=>`<p>→ ${esc(a)}</p>`).join('')}</div>`:''}${r.model_summary?`<div class="result-item"><strong>模型补充摘要 · 请核实</strong><p>${esc(r.model_summary)}</p></div>`:''}${r.sources.map((s,i)=>citation(s,i)).join('')}<details class="trace" open><summary>执行轨迹 · ${esc(run.model_mode)} · ${number(run.duration_ms)} ms</summary>${run.trace.map(t=>`<div class="trace-step">${icon(t.status==='success'?'check':'clock')}<b>${esc(t.step)}</b><small>${esc(t.tool)} · ${esc(t.detail)}</small></div>`).join('')}</details><p class="form-note" style="margin-top:12px">${esc(r.scope)}<br>执行编号：${esc(run.id)}</p>`;}
function citation(s,i){return `<div class="citation"><h4>[${i+1}] ${esc(s.title)}</h4><p>${esc(s.excerpt)}</p><small>版本 v${s.version} · 片段 ${esc(s.chunk_id)} · 词项匹配得分 ${s.score}</small></div>`;}
async function renderKnowledge(){state.documents=await api('/knowledge');return heading('让团队经验，成为共同的答案。','汇集 SOP、质量标准与业务规则。先过滤权限，再检索证据。',can('admin')?`<button class="btn primary" data-action="new-document">${icon('plus')}添加知识</button>`:'','KNOWLEDGE / 企业知识库')+`<div class="knowledge-layout"><section class="panel"><div class="panel-head"><h2>知识文档</h2>${badge(state.documents.length+' 份可见文档')}</div><div class="panel-body">${state.documents.map(d=>`<article class="doc-card">${badge(d.category)}<h3>${esc(d.title)}</h3><p>${esc(d.content)}</p><span class="doc-meta">v${d.version} · ${esc(names[d.min_role])}可见范围</span></article>`).join('')||empty('暂无可见文档')}</div></section><section class="panel" style="align-self:start"><div class="panel-head"><h2>向企业知识提问</h2>${icon('spark')}</div><div class="panel-body"><form id="knowledge-form"><textarea name="question" maxlength="2000" required placeholder="例如：生产进度不足时，如何处理交期风险？" aria-label="知识库问题"></textarea><div class="form-actions"><button class="btn primary" type="submit">${icon('search')}检索知识</button></div></form><div id="knowledge-result">${empty('每个回答都应有出处。\n输入问题，查看与你权限匹配的知识片段。')}</div></div></section></div>`;}
async function renderSystem(){const [integrations,logs]=await Promise.all([api('/integrations'),api('/audit')]);return heading('连接业务系统，守住操作边界。','真实连接状态、角色权限和审计记录，清晰可查。',`<a class="btn" href="/docs" target="_blank" rel="noopener">API 文档 ${icon('arrow')}</a>`,'SYSTEM / 集成与审计')+`<div class="connector-grid">${integrations.map(i=>`<article class="connector">${icon(i.name==='Ollama'?'spark':'globe')}<h3>${esc(i.name)}</h3>${badge({configured:'已配置 · 未测连通性',not_configured:'未配置',planned:'待实现'}[i.status],i.status==='configured'?'':'gray')}<p>${esc(i.detail)}</p></article>`).join('')}</div><section class="panel"><div class="panel-head"><h2>操作审计</h2><span class="muted" style="font-size:10px">最近 100 条 · 当前企业</span></div>${logs.length?`<div class="table-wrap"><table><thead><tr><th>操作时间</th><th>操作者</th><th>操作类型</th><th>资源 ID</th><th>请求追踪</th></tr></thead><tbody>${logs.map(l=>`<tr><td>${esc(new Date(l.created_at).toLocaleString('zh-CN'))}</td><td>${esc(l.actor_name||l.actor)}</td><td>${badge(l.action,'blue')}</td><td>${esc(l.entity_id)}</td><td><small>${esc(l.request_id)}</small></td></tr>`).join('')}</tbody></table></div>`:empty('暂无审计记录')}</section>`;}
let modalLastFocus;
function modal(title,body){modalLastFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" tabindex="-1"><div class="modal-head"><h2 id="modal-title">${esc(title)}</h2><button class="icon-btn" data-action="close-modal" aria-label="关闭弹窗">${icon('close')}</button></div>${body}</section></div>`;$('.modal').focus();}
function closeModal(){$('#modal-root').innerHTML='';modalLastFocus?.focus();}
function orderModal(id){const o=state.orders.find(o=>o.id===id);if(!o)return;const stageIndex=Object.keys(stageNames).indexOf(o.stage);modal(o.number+' · 订单跟进',`<div class="notice">${esc(o.customer_name)} · ${esc(o.product_name)} · ${number(o.quantity)} 件<br>${esc(o.risk.reason)} · 约定出运 ${esc(o.due_date)}</div><form id="order-form" data-id="${esc(id)}"><div class="form-grid"><label class="field">当前 / 下一节点<select name="stage" ${can('admin','operations')?'':'disabled'}>${Object.entries(stageNames).filter((_,i)=>i===stageIndex||i===stageIndex+1).map(([s,n])=>`<option value="${s}">${n}</option>`).join('')}</select></label>${numericField('累计生产进度 %','progress',o.progress,1,o.progress,100)}<label class="field full">跟进记录<textarea name="note" maxlength="2000">${esc(o.notes)}</textarea></label></div><label class="check-label"><input type="checkbox" name="quality_passed">已确认验货通过（进入出运节点前必填）</label><p class="form-note" style="margin-top:12px">验货及后续节点要求累计生产进度 100%。实际延误原因须人工核实。</p><div class="form-actions"><button class="btn" type="button" data-action="close-modal">关闭</button>${can('admin','operations')&&o.stage!=='closed'?'<button class="btn primary" type="submit">保存跟进</button>':''}</div></form>${can('admin')&&Number(o.paid)<Number(o.total)?`<hr style="border:0;border-top:1px solid #edf0e8;margin:25px 0"><form id="payment-form" data-id="${esc(id)}"><label class="field">登记已到账货款 USD · 尚欠 ${usd(Number(o.total)-Number(o.paid))}<input class="input" type="number" name="amount" required step=".01" min=".01" max="${(Number(o.total)-Number(o.paid)).toFixed(2)}"></label><div class="form-actions"><button class="btn" type="submit">确认到账并登记</button></div></form>`:''}`);}
function newCustomer(){modal('新增客户',`<form id="customer-form"><div class="form-grid"><label class="field full">客户名称<input class="input" name="name" required minlength="2" maxlength="150"></label><label class="field">国家 / 地区<input class="input" name="country" required maxlength="80"></label><label class="field">来源渠道<select name="channel"><option>独立站</option><option>Shopify</option><option>Faire</option><option>展会</option><option>其他</option></select></label><label class="field full">联系邮箱<input class="input" type="email" name="email" required maxlength="200"></label></div><div class="form-actions"><button class="btn primary" type="submit">保存客户</button></div></form>`);}
function newDocument(){modal('添加企业知识',`<form id="document-form"><div class="form-grid"><label class="field full">文档标题<input class="input" name="title" required minlength="2" maxlength="150"></label><label class="field">知识分类<input class="input" name="category" required minlength="2" maxlength="50" placeholder="例如：质量标准"></label><label class="field">可见范围<select name="min_role"><option value="viewer">全部角色</option><option value="sales">业务员及管理员</option><option value="operations">跟单员及管理员</option><option value="admin">仅管理员</option></select></label><label class="field full">知识正文<textarea name="content" required minlength="20" maxlength="30000" style="min-height:180px" placeholder="输入经业务负责人确认的标准、经验或处理流程…"></textarea></label></div><div class="form-actions"><button class="btn primary" type="submit">保存并纳入检索</button></div></form>`);}
document.addEventListener('click',async event=>{
  const b=event.target.closest('button,a[data-nav]');if(!b||b.disabled)return;
  try{
    if(b.dataset.nav){if(b.dataset.risk)state.orderFilter='risk';await navigate(b.dataset.nav);}
    else if(b.dataset.agent){state.selectedAgent=b.dataset.agent;await navigate('agents');}
    else if(b.dataset.selectAgent){state.selectedAgent=b.dataset.selectAgent;$$('.agent-card').forEach(c=>c.classList.toggle('selected',c.dataset.selectAgent===state.selectedAgent));$('#selected-agent-name').textContent=state.agents.find(a=>a.id===state.selectedAgent).name;$('#agent-form textarea').value=agentQuestions[state.selectedAgent];$('#agent-output').innerHTML='';}
    else if(b.dataset.order)orderModal(b.dataset.order);
    else if(b.dataset.orderFilter){state.orderFilter=b.dataset.orderFilter;$$('[data-order-filter]').forEach(c=>c.classList.toggle('active',c===b));$('#order-list').innerHTML=filteredOrders();}
    else if(b.dataset.quoteProduct){state.quoteProduct=b.dataset.quoteProduct;await navigate('quotes');}
    else if(b.dataset.approve){const q=state.quotes.find(q=>q.id===b.dataset.approve);modal('人工确认报价',`<div class="notice">请核对客户、成本、税率和交期后确认审批。审批不代表已向客户发送。</div><p class="preline">${esc(q.product_name)} · ${esc(q.customer_name)}<br>报价总额 ${usd(q.total)} · 目标毛利 ${(Number(q.margin)*100).toFixed(1)}%</p><div class="form-actions"><button class="btn" data-action="close-modal">返回核对</button><button class="btn primary" data-confirm-approve="${esc(q.id)}">确认审批通过</button></div>`);}
    else if(b.dataset.confirmApprove){await post('/quotes/'+b.dataset.confirmApprove+'/approve');closeModal();toast('报价审批通过');await navigate('quotes');}
    else if(b.dataset.convert){b.disabled=true;await post('/quotes/'+b.dataset.convert+'/convert');toast('已创建订单，可在订单与履约中跟进');await navigate('quotes');}
    else if(b.dataset.contact){b.disabled=true;await post('/customers/'+b.dataset.contact+'/contact');toast('已记录今日联系时间；未发送任何消息');await navigate('customers');}
    else if(b.dataset.run){const run=state.runs.find(r=>r.id===b.dataset.run);$('#agent-output').innerHTML=agentResult(run);$('#agent-output').scrollIntoView({behavior:'smooth',block:'start'});}
    else if(b.dataset.action==='logout'){await post('/auth/logout');state.user=null;renderLogin();}
    else if(b.dataset.action==='menu')$('.sidebar').classList.toggle('open');
    else if(b.dataset.action==='close-modal')closeModal();
    else if(b.dataset.action==='new-customer')newCustomer();
    else if(b.dataset.action==='new-document')newDocument();
    else if(b.dataset.action==='reload')await navigate(state.page);
  }catch(err){b.disabled=false;toast(err.message,true);}
});
document.addEventListener('input',event=>{const target=event.target;if(target.dataset.search){state.query=target.value;const q=state.query.toLowerCase();if(target.dataset.search==='products')$('#product-list').innerHTML=productCards(state.products.filter(p=>(p.name+p.sku).toLowerCase().includes(q)));if(target.dataset.search==='orders')$('#order-list').innerHTML=filteredOrders();if(target.dataset.search==='customers')$('#customer-list').innerHTML=customerTable(state.customers.filter(c=>(c.name+c.country+c.channel).toLowerCase().includes(q)));}});
document.addEventListener('submit',async event=>{
  event.preventDefault();const form=event.target;const data=Object.fromEntries(new FormData(form));const buttons=$$('button[type="submit"]',form);buttons.forEach(b=>b.disabled=true);
  try{
    if(form.id==='login-form'){state.user=await post('/auth/login',data);shell();await navigate(location.hash.slice(1)||'overview');}
    if(form.id==='quote-form'){data.quantity=Number(data.quantity);data.margin=String(Number(data.margin)/100);data.duty_rate=String(Number(data.duty_rate)/100);const save=event.submitter?.value==='save';const r=await post(save?'/quotes':'/quotes/preview',data);$('#quote-result').innerHTML=quoteResult(r);if(save){toast('报价已保存，等待人工审批');state.quotes=await api('/quotes');$('#quotes-list').innerHTML=quoteTable();}}
    if(form.id==='order-form'){const o=state.orders.find(o=>o.id===form.dataset.id);await api('/orders/'+o.id,{method:'PATCH',body:JSON.stringify({stage:data.stage,progress:Number(data.progress),version:o.version,note:data.note,quality_passed:data.quality_passed==='on'})});closeModal();toast('订单跟进已保存');await navigate('orders');}
    if(form.id==='payment-form'){const o=state.orders.find(o=>o.id===form.dataset.id);await post('/orders/'+o.id+'/payments',{amount:data.amount,version:o.version});closeModal();toast('收款已登记并写入审计');await navigate('orders');}
    if(form.id==='customer-form'){await post('/customers',data);closeModal();toast('客户已保存');await navigate('customers');}
    if(form.id==='document-form'){await post('/knowledge',data);closeModal();toast('知识文档已保存');await navigate('knowledge');}
    if(form.id==='agent-form'){const generation=state.generation;$('#agent-output').innerHTML='<div class="loading">正在执行受控工具流程，检索企业知识…</div>';try{const run=await post('/agents/run',{agent:state.selectedAgent,question:data.question});if(generation===state.generation&&$('#agent-output')){$('#agent-output').innerHTML=agentResult(run);$('#run-history').innerHTML=runHistory(await api('/agents/runs'));}}catch(error){if(generation===state.generation&&$('#agent-output'))$('#agent-output').innerHTML=empty(error.message);throw error;}}
    if(form.id==='knowledge-form'){const generation=state.generation;$('#knowledge-result').innerHTML='<div class="loading">正在权限范围内检索…</div>';try{const result=await post('/knowledge/search',data);if(generation===state.generation&&$('#knowledge-result'))$('#knowledge-result').innerHTML=`<p class="preline">${esc(result.answer)}</p>${result.model_error?`<div class="notice">${esc(result.model_error)}</div>`:''}${result.sources.map(citation).join('')}`;}catch(error){if(generation===state.generation&&$('#knowledge-result'))$('#knowledge-result').innerHTML=empty(error.message);throw error;}}
  }catch(err){if(form.id==='login-form')$('.login-error',form).textContent=err.message;else toast(err.message,true);}
  finally{buttons.forEach(b=>b.disabled=false);}
});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'&&state.user){event.preventDefault();navigate('knowledge');}const dialog=$('.modal');if(event.key==='Tab'&&dialog){const elements=$$('button,input,select,textarea,[tabindex="0"]',dialog).filter(e=>!e.disabled);const first=elements[0],last=elements.at(-1);if(event.shiftKey&&(document.activeElement===first||document.activeElement===dialog)){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
window.addEventListener('hashchange',()=>{if(state.user)navigate(location.hash.slice(1),false);});
(async()=>{try{state.config=await api('/config');try{state.user=await api('/auth/me');}catch{}if(state.user){shell();await navigate(location.hash.slice(1)||'overview');}else renderLogin();}catch(err){$('#app').innerHTML=`<div class="boot"><span class="brand-mark">H</span><p>${esc(err.message)}</p><p>请确认本地服务已启动，然后刷新页面。</p></div>`;}})();
